### ISSUE TITLE
Custom text selection style is hard to read

### ISSUE THREAD

**Issue by sharrie** [DataSF/datasf.github.io#36]
Currently, the website has different ::selection styles depending on the browser. Perhaps using a color close to the (numerous!) defaults or the primary color + white text for all browsers is more readable. I can submit a PR with whatever's preferred if you're open to contributors :)

**Current on Firefox**
<img width="806" alt="screen shot 2016-03-14 at 2 39 30 pm" src="https://cloud.githubusercontent.com/assets/2240408/13760926/cf32dbae-e9f2-11e5-8ee2-1d7d878f005b.png">

**Current on Chrome**
<img width="785" alt="screen shot 2016-03-14 at 2 25 17 pm" src="https://cloud.githubusercontent.com/assets/2240408/13760477/9cebe570-e9f0-11e5-91e3-8af44b6a1600.png">

**#B4D5FF**
<img width="781" alt="screen shot 2016-03-14 at 3 55 15 pm" src="https://cloud.githubusercontent.com/assets/2240408/13762591/33fd31f6-e9fd-11e5-9850-4623fc4cf0f9.png">

**Primary Color + White Text**
<img width="789" alt="screen shot 2016-03-14 at 2 23 03 pm" src="https://cloud.githubusercontent.com/assets/2240408/13760430/54d45fce-e9f0-11e5-95e2-0ebb208f132c.png">

**Comment by jasonlally** [comment]
Yes, please submit a PR. I apologize, I think that was left over from a template we originally started with. I've been meaning to clean those up, but would welcome the help!

**Comment by jasonlally** [comment]
Let's go with Primary + White
