### ISSUE TITLE
Bad link on open data release toolkit page

### ISSUE THREAD

**Issue by shua123** [DataSF/datasf.github.io#55]
On https://datasf.org/resources/open-data-release-toolkit/ the "open data publishing process" link is a broken dev link.
![image](https://user-images.githubusercontent.com/1593537/27714931-9cbffac8-5cf9-11e7-8d74-afadd9f36bcc.png)

**Comment by jasonlally** [comment]
Thanks! 

Fixed via commit 470f5e67c5bd416
